### ISSUE TITLE
Unable to backup RWO PVCs

### ISSUE THREAD

**Issue by gi8lino** [vshn/k8up#110]
Hi

When trying to backup RWO PVCs K8up doesn't check on which node the pod with said PVC mounted is running.
Since RWO volumes can only be mounted multiple times on the same node, K8up should check on which node the pod is running and create the backupjob on the same node.

As of now, the backupjob will never start since it's not running on the same node.

Is it possible to implement that check?

As a workaround we'll try to add an application aware backup command to the pod; basically "tar"-ing all of the files to stdout. But it would be much nicer if we could just use the PVC annotation.

Many thanks,
gi8lino

**Comment by Kidswiss** [comment]
HI @gi8lino 

Thank you for opening an issue.

It's correct that K8up is currently not capable of backing up RWO PVCs as mentioned here: https://k8up.io/docs/0.1.9/index.html#_current_limitations

K8up will only schedule one wrestic worker per namespace. So if the namespace contains multiple RWO PVCs it's sometimes not even possible to schedule it, because they could be mounted on different hosts.

We're aware that this is a problem and using the backup commands is currently our recommended workaround for that.

Best
Simon

**Comment by gi8lino** [comment]
for the sake of completeness here is the backup command:
`k8up.syn.tools/backupcommand: tar czvf - /app`

**Comment by Kidswiss** [comment]
@gi8lino Is it okay for you that we close here?
