### ISSUE TITLE
Ability to set SecurityContext for the various job types

### ISSUE THREAD

**Issue by Kidswiss** [vshn/k8up#263]
## Summary

**As** a K8up user
**I want** to specify what user is used for the wrestic pods
**So that** it's able to backup all files

## Context

Wrestic 2.0 runs as root on purpose, there are some cases where PVCs can't be read otherwise.

But there also K8s distributions that do not want you to run the pods as root, like OpenShift. So we need a way to specify the `runAs` for the jobs so we can cover all the use cases.

Bonus: it would be great if the operator can determine this by itself. E.g. if the operator is running on OpenShift it will set a user and if running on another distro it will run as root.

## Out of Scope

* TBD

## Further links

* https://github.com/vshn/wrestic/pull/38
* https://github.com/vshn/wrestic/pull/19

## Acceptance criteria

*Given* a k8s cluster
*When* job is triggered
*Then* it will run with the right user

## Implementation Ideas

* none yet

**Comment by ccremer** [comment]
`runAs` can often be insufficient when trying to access files from PVCs. `runAsGroup` or `fsGroup` are also relevant.

I propose to rather to set the [SecurityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for either Pod or a container instead of just a single property
