### ISSUE TITLE
Use imagePullPolicy IfNotPresent for backup jobs

### ISSUE THREAD

**Issue by huerlisi** [vshn/k8up#336]
## Summary

**As** "DevOps"\
**I want** "the backup jobs to reuse present Docker images"\
**So that** "load is reduced and DockerHub quotas are not exceeded"

## Context

The operator schedules `Job`s to run the actual backups. This is done using the `wrestic` Docker images. The `Job`s then create the actual `Pod`s to do the work. `Job`s do contain a `spec` section for the `containers` where parameters like `image` are declared. One possible parameter is `imagePullPolicy` which has a default of `Always`. This triggers Kubernetes to always pull the latest image from the respective Docker registry.

It is good practice to use explicitly tagged images in `Job` specs and to not re-use tags for Docker images. If these practices are followed, it is again good practice to use an `imagePullPolicy` of `IfNotPresent` so Docker images on Kubernetes nodes are re-used. The `imagePullPolicy` is only needed for untagged images or if some generic tags like `latest` are used.

`k8up` comes with a helm chart where one can specify the `imagePullPolicy` for the controller. This value is defaulting as per best practices to `IfNotPresent`. It also allows to set the `image` used for backups as `k8up.backupImage` using `image` and `tag` keys, and provides defaults setting a specific `tag` as per best practices. 

It would be great to use a default of an `imagePullPolicy` of `IfNotPresent` when creating the backup `Job`s and maybe allow overriding this using a `k8up.backupImage.imagePullPolicy` field if really needed.

This got some priority due to DockerHub having introduced rate limits for their public offering of Open Source Docker images. When using many backup jobs, the default rate limits of 100 pulls per 6h can quickly be reached.

## Implementation Ideas

I quickly checked the source code of the controller and found the following in `job/job.go` that looks like the place for changing this:

```go
// GenerateGenericJob returns a generic batchv1.job for further use.
func GenerateGenericJob(obj Object, config Config) (*batchv1.Job, error) {
  job := &batchv1.Job{
    ObjectMeta: metav1.ObjectMeta{
      Name:      obj.GetMetaObject().GetName(),
      Namespace: obj.GetMetaObject().GetNamespace(),
      Labels: map[string]string{
        K8uplabel:     "true",
        K8upTypeLabel: obj.GetType().String(),
      },
    },
    Spec: batchv1.JobSpec{
      Template: corev1.PodTemplateSpec{
        Spec: corev1.PodSpec{
          RestartPolicy: corev1.RestartPolicyOnFailure,
          Containers: []corev1.Container{
            {
              Name:      obj.GetMetaObject().GetName(),
              Image:     cfg.Config.BackupImage,
              Resources: config.Obj.GetResources(),
            },
          },
        },
      },
    },
  }
```

Thanks a lot for this great project, and greetings from snowy Zug.

**Comment by ccremer** [comment]
Hi

Thanks for the request!
Firstly, all our latest docker images or also available on quay.io also because of Docker's pull limit. As a quick fix, just change `docker.io` to `quay.io` in the helm values and you should have no pull problems :)

Secondly, according to the [API documentation](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#image), if the image pull policy is unspecified, the effective image pull policy depends on whether `latest` is in the image string or not. If yes, `Always` is applied, otherwise it defaults to `IfNotPresent`. Make sure to not use `latest` in `k8up.backupImage.tag` to profit from this behaviour.

However, the code you posted is from the master branch, where the image pull policy is already left unspecified. If you're using K8up v0.x, the pull policy is hardcoded to `Always`. I reckon this is the reason why you opened this request.

The current code in the master branch is a complete internal rewrite, but not yet released. K8up v1.0 should be around soon where the second point applies. For now, switching to quay.io is all you can do to workaround Docker's pull limit.

Does that help for the time being?

Greetings from HomeOffice :)

**Comment by huerlisi** [comment]
Just figured out the thing with `quay.io` and switched some minutes ago, so all good on that front!

Didn't realize about the pull policy being changed between v0.x and `master`. So I think my original request is already perfectly handled for the future and the issue fixed locally for now.

Thanks a lot for the quick update!

**Comment by ccremer** [comment]
Perfect!
We might want to make this configurable from the chart later, but I don't think we'd need that in v1.0, rather v2.
