### ISSUE TITLE
unexpected status code 200 while pushing to pushgateway 

### ISSUE THREAD

**Issue by gi8lino** [vshn/k8up#396]
## Describe the bug

the issue with the unexpected status code 200 is back: https://github.com/vshn/k8up/issues/106

## Logs

If applicable, add logs to help explain your problem.
```console
I0312 12:37:07.416570       1 handler.go:44] wrestic/statsHandler/promStats "level"=0 "msg"="sending prometheus stats"  "url"="http://prometheus-pushgateway.monitoring.svc.cluster.local:9091"
E0312 12:37:07.421030       1 backup.go:96] wrestic "msg"="prometheus send failed" "error"="unexpected status code 200 while pushing to http://prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics/job/restic_backup/instance/backup: "  
I0312 12:37:07.421070       1 main.go:177] wrestic "level"=0 "msg"="all pod commands have finished successfully"  
```

## Environment (please complete the following information):

- Image Version: e.g. v1.0.3
- k3s version v1.20.4+k3s1 (838a906a)
- go version go1.15.8

**Comment by Kidswiss** [comment]
Hi @gi8lino 

Thanks for reporting this!

That's odd, the fix for this has been merged a long time ago and the tag worked for you then.

We may have to check if some commit slipped in that changed the prometheus dependencies.

**Comment by cimnine** [comment]
It turns out the PR that should have fixed this (https://github.com/vshn/wrestic/pull/23) was never actually merged. A more recent PR (https://github.com/vshn/wrestic/pull/65) has now been merged instead. I don't have information on when a new restic release will be released.

We have to see whether we try to include improvements to the parsing of the restic output in the next release as well – or if we do a release in the meantime.

@Kidswiss maybe you have more to say on this topic?

**Comment by tobru** [comment]
Thanks for your feedback
